# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "filter" ]
  pull_request:
    branches: [ "master", "filter" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
      
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: src/github.com/${{ github.repository }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install dependencies
      run: |
        go get -u golang.org/x/lint/golint
        
    - name: Build
      run: |
        go env
        make build && make build GOOS=windows

    - name: Test
      run: make test
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: atomdns
        path: |
          filter
